---
title: "Proyecto fase 3 analisis QAP"
output:
  pdf_document: default
  html_document: default
  Integrantes: Juan David Roldán, Diego García, Gabriel Gómez y Miller Puentes
---

# Punto 1

```{r setup, include=FALSE}

# Librerías

library(readxl)
library(magrittr)
library(dplyr)

library(ISLR)
library(tidyverse)
library(Hmisc)
library(sna)
library(igraph)
library(network)
library(readr)

#----------------------------------------------------------------------------------------------------
# Lectura y adecuación de datos

Arcos <- read.csv("/Users/gabrielgomez/Library/CloudStorage/OneDrive-UniversidaddelosAndes/Analytics en Redes Sociales/Proyecto en R/Arcos_f.csv", header=TRUE)
colnames(Arcos)<-c("from","to")


Nodos <- read_excel("/Users/gabrielgomez/Library/CloudStorage/OneDrive-UniversidaddelosAndes/Analytics en Redes Sociales/Proyecto en R/Base-inicial.xlsx")
Nodos <- Nodos %>% select(-c("Principales inversionistas"))
names(Nodos)[1] <- "Id"


# Para convertir los Id en números
Nodos$Id <- as.factor(Nodos$Id)
numeros <- seq_along(Nodos$Id)
Nodos$Id_num <- numeros

Nodos_num <- select(Nodos, Id, Id_num)

ArcosNodos <- left_join(Arcos, Nodos_num, by = c("from" = "Id"))
ArcosNodos <- ArcosNodos %>% select(-from)
ArcosNodos <- ArcosNodos %>%  rename(from = Id_num)

ArcosNodos <- left_join(ArcosNodos, Nodos_num, by = c("to" = "Id"))
ArcosNodos <- ArcosNodos %>% select(-to)
ArcosNodos <- ArcosNodos %>%  rename(to = Id_num)

# Finalmente se reemplazan los números
Nodos <- Nodos %>% select(-Id)
Nodos <- Nodos %>%  rename(Id = Id_num)

Arcos <- ArcosNodos

# Crear un grafo a partir de los datos de arcos
grafo <- graph_from_data_frame(Arcos)

# Calcular el PageRank de cada nodo en el grafo
pr_red <- page_rank(grafo, directed = TRUE)

# Calcular el grado de cada nodo en el grafo
grados <- igraph::degree(grafo)


```

```{r}
# Inicializar matriz de adyacencia con ceros
matriz_adyacencia <- matrix(0, nrow = nrow(Nodos), ncol = nrow(Nodos))
rownames(matriz_adyacencia) <- colnames(matriz_adyacencia) <- Nodos$Id  # Establecer nombres de fila y columna

# Llenar matriz de adyacencia con valores de conexión
for (i in 1:nrow(Arcos)) {
  from <- as.character(Arcos[i, "from"])
  to <- as.character(Arcos[i, "to"])
  if (from %in% rownames(matriz_adyacencia) && to %in% colnames(matriz_adyacencia)) {
    matriz_adyacencia[from, to] <- 1
    matriz_adyacencia[to, from] <- 1  # Asegurar simetría en la matriz (grafo no dirigido)
  }
}


y <- matriz_adyacencia


# Crear x1 asociado al grado total
grado_total <- igraph::degree(grafo,mode = "all")

grado_total <- (grado_total-min(grado_total))/(max(grado_total)-min(grado_total))

# Crear la matriz x1 asociada al GRADO
x1 <- matrix(NA,nrow(Nodos),nrow(Nodos))
for(i in 1:nrow(Nodos)){
  for(j in 1:nrow(Nodos)){
    x1[i,j]<-1- abs(grado_total[i]-grado_total[j])
  }
}

# Crear la matriz x2 asociada al betweenness
bet <- igraph::betweenness(grafo)

bet <- (bet-min(bet))/(max(bet)-min(bet))

x2 <- matrix(NA,nrow(Nodos),nrow(Nodos))
for(i in 1:nrow(Nodos)){
  for(j in 1:nrow(Nodos)){
    x2[i,j]<-1-abs(bet[i]-bet[j])
  }
}

# Crear la matriz x3 asociada a la cantidad total de inversiones realizadas por las compa??as.
x3 <- matrix(NA,nrow(Nodos),nrow(Nodos))
for(i in 1:nrow(Nodos)){
  for(j in 1:nrow(Nodos)){
    x3[i,j]<-1-abs(Nodos$`Number of Investments`[i] -Nodos$`Number of Investments`[j])
  }
}



# Crear la matriz x4 asociada al n?mero de inversiones l?deres
x4 <- matrix(NA,nrow(Nodos),nrow(Nodos))
for(i in 1:nrow(Nodos)){
  for(j in 1:nrow(Nodos)){
    x4[i,j]<-1-abs(Nodos$`Number of Lead Investments`[i] -Nodos$`Number of Lead Investments`[j])
  }
}

# Crear la matriz x5 asociada al n?mero de diversidad de inversiones
x5 <- matrix(NA,nrow(Nodos),nrow(Nodos))
for(i in 1:nrow(Nodos)){
  for(j in 1:nrow(Nodos)){
    x5[i,j]<-1-abs(Nodos$`Number of Diversity Investments`[i] -Nodos$`Number of Diversity Investments`[j])
  }
}


# Crear la matriz x6 asociada al n?mero de salidas
x6 <- matrix(NA,nrow(Nodos),nrow(Nodos))
for(i in 1:nrow(Nodos)){
  for(j in 1:nrow(Nodos)){
    x6[i,j]<-1-abs(Nodos$`Number of Exits`[i] -Nodos$`Number of Exits`[j])
  }
}

# Crear la matriz x7 asociada al n?mero de inversores l?deres
x7 <- matrix(NA,nrow(Nodos),nrow(Nodos))
for(i in 1:nrow(Nodos)){
  for(j in 1:nrow(Nodos)){
    x7[i,j]<-1-abs(Nodos$`Number of Lead Investors`[i] -Nodos$`Number of Lead Investors`[j])
  }
}


# Crear la matriz x8 asociada al n?mero de rondas de financiamiento
x8 <- matrix(NA,nrow(Nodos),nrow(Nodos))
for(i in 1:nrow(Nodos)){
  for(j in 1:nrow(Nodos)){
    x8[i,j]<-1-abs(Nodos$`Number of Funding Rounds`[i] -Nodos$`Number of Funding Rounds`[j])
  }
}

# Crear la matriz x9 asociada a la ?ltima cantidad de financiaci?n en USD
x9 <- matrix(NA,nrow(Nodos),nrow(Nodos))
for(i in 1:nrow(Nodos)){
  for(j in 1:nrow(Nodos)){
    x9[i,j]<-1-abs(Nodos$`Last Funding Amount Currency (in USD)`[i] -Nodos$`Last Funding Amount Currency (in USD)`[j])
  }
}


# Crear la matriz x10 asociada a la cantidad total de eventos en los que la organizaci?n ha aparecido
x10 <- matrix(NA,nrow(Nodos),nrow(Nodos))
for(i in 1:nrow(Nodos)){
  for(j in 1:nrow(Nodos)){
    x10[i,j]<-1-abs(Nodos$`Number of Events`[i] -Nodos$`Number of Events`[j])
  }
}

```

```{r}
#Se realiza el modelo QAP
qap_fit <-netlogit(y,list(x1, x2, x3, x4, x5, x6, x7, x9, x10),rep = 10) 
# Ver los resultados esperados al finalizar las matrices calculadas
summary(qap_fit)
```

```{r}
#Se realiza el modelo QAP
qap_fit <-netlogit(y,list(x1, x2, x3, x4, x5, x7, x9, x10),rep = 10) 
# Ver los resultados esperados al finalizar las matrices calculadas
summary(qap_fit)
```

```{r}
#Se realiza el modelo QAP
qap_fit <-netlogit(y,list(x2, x3, x4, x5, x7, x9, x10),rep = 10) 
# Ver los resultados esperados al finalizar las matrices calculadas
summary(qap_fit)
```
```{r}
#Se realiza el modelo QAP
qap_fit <-netlogit(y,list(x2, x3, x4, x5, x7, x10),rep = 10) 
# Ver los resultados esperados al finalizar las matrices calculadas
summary(qap_fit)
```
```{r}
#Se realiza el modelo QAP
qap_fit <-netlogit(y,list(x2, x4, x5, x7, x10),rep = 10) 
# Ver los resultados esperados al finalizar las matrices calculadas
summary(qap_fit)
```
```{r}
#Se realiza el modelo QAP
qap_fit <-netlogit(y,list(x4, x5, x7, x10),rep = 10) 
# Ver los resultados esperados al finalizar las matrices calculadas
summary(qap_fit)
```


# Punto 1


```{r}

# Librerías
  
  library(readxl)
  library(magrittr)
  library(dplyr)
  library(ISLR)
  library(tidyverse)
  library(Hmisc)
  library(sna)
  library(igraph)
  library(network)
  library(readr)
  library(intergraph)
  library(ergm)
  library(network)
  library(tergm)

  #----------------------------------------------------------------------------------------------------
  # Lectura y adecuación de datos
  
  Arcos <- read.csv("OneDrive_1_6-3-2024/Arcos_short.csv", header=TRUE)
  colnames(Arcos)<-c("from","to")
  
  
  Nodos <- read_excel("OneDrive_1_6-3-2024/Base-inicial.xlsx")
  Nodos <- Nodos %>% select(-c("Principales inversionistas"))
  names(Nodos)[1] <- "Id"
  
  
  # Para convertir los Id en números
  Nodos$Id <- as.factor(Nodos$Id)
  numeros <- seq_along(Nodos$Id)
  Nodos$Id_num <- numeros
  
  Nodos_num <- select(Nodos, Id, Id_num)
  
  ArcosNodos <- left_join(Arcos, Nodos_num, by = c("from" = "Id"))
  ArcosNodos <- ArcosNodos %>% select(-from)
  ArcosNodos <- ArcosNodos %>%  rename(from = Id_num)
  
  ArcosNodos <- left_join(ArcosNodos, Nodos_num, by = c("to" = "Id"))
  ArcosNodos <- ArcosNodos %>% select(-to)
  ArcosNodos <- ArcosNodos %>%  rename(to = Id_num)
  
  # Finalmente se reemplazan los números
  Nodos <- Nodos %>% select(-Id)
  Nodos <- Nodos %>%  rename(Id = Id_num)
  
  Arcos <- ArcosNodos
  
  
#Hacemos imputaciones de variables, reemplazando los NA con 0
  
  Nodos$'Number of Lead Investments'[is.na(Nodos$'Number of Lead Investments')] <- 0
  Nodos$'Number of Investments'[is.na(Nodos$'Number of Investments')] <- 0
  Nodos$'Number of Exits'[is.na(Nodos$'Number of Exits')] <- 0
  Nodos$'Number of Diversity Investments'[is.na(Nodos$'Number of Diversity Investments')] <- 0
  Nodos$'Number of Lead Investors'[is.na(Nodos$'Number of Lead Investors')] <- 0
  Nodos$'Number of Funding Rounds'[is.na(Nodos$'Number of Funding Rounds')] <- 0
  Nodos$'Last Funding Amount Currency (in USD)'[is.na(Nodos$'Last Funding Amount Currency (in USD)')] <- 0
  Nodos$'Number of Events'[is.na(Nodos$'Number of Events')] <- 0

#----------------------------------------------------------------------------------------------------
# 1. Reconocer e implementar el modelo estadístico argm.
  
  
#Removemos los Nodos que se conectan a ellos mismos
  
  Arcos <- Arcos[Arcos$from != Arcos$to, ]
  
#Creamos red e integramos atributos
  
  red <- graph_from_data_frame(Arcos, Nodos$Id, directed=TRUE)
  V(red)$N_LeadInvestments <- Nodos$`Number of Lead Investments`
  V(red)$N_Inversiones <- Nodos$`Number of Investments`
  V(red)$N_Exits <- Nodos$`Number of Exits`
  V(red)$N_Inversiones_Diversity <- Nodos$`Number of Diversity Investments`
  V(red)$N_LeadInvestors <- Nodos$`Number of Lead Investors`
  V(red)$N_Funding_Rounds <- Nodos$`Number of Funding Rounds`
  V(red)$Last_Funding_Amount <- Nodos$`Last Funding Amount Currency (in USD)`
  V(red)$N_Events<- Nodos$`Number of Events`

  class(red)
  
#Convertimos a un objeto Network y validamos la integración de atributos
  
  N_red <- asNetwork(red)
  class(N_red)
  
  
# Correr el ERGM
  
  m1 <- ergm(N_red~ edges + transitiveties + nodematch("N_LeadInvestments")+ nodematch("N_Inversiones")+ nodematch("N_Exits")
             + nodematch("N_Inversiones_Diversity") + nodematch("N_LeadInvestors") + nodematch("N_Funding_Rounds")
             + nodematch("Last_Funding_Amount") + nodematch("N_Events"),nreps = 1000)
  summary(m1)
  exp(coef(m1))
  
  gf1 <- gof(m1)
  par(mfrow = c(3,2))
  plot(gf1, main = "")


```